app/property/forms.py
from flask import request
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, IntegerField, FormField, BooleanField, SelectField
from wtforms.validators import ValidationError, DataRequired, Length
from flask_babel import _, lazy_gettext as _l
from app.models import User, Company
import pycountry

class CountrySelectField(SelectField):
    def __init__(self, *args, **kwargs):
        super(CountrySelectField, self).__init__(*args, **kwargs)
        self.choices = [(country.alpha_2, country.name) for country in pycountry.countries]

class AddressForm(FlaskForm):
#    street_type = StringField(_l('Street type'), validators=[DataRequired()])
    street_name = StringField(_l('Street'), validators=[DataRequired()])
    street_number = IntegerField(_l('Number'), validators=[DataRequired()])
    city = StringField(_l('City'), validators=[DataRequired()])
    postalcode = IntegerField(_l('Postal Code'), validators=[DataRequired()])
    province = StringField(_l('Province'))
    region = StringField(_l('Region'))
    country = CountrySelectField(_l('Country'))

class PropertyDescription(FlaskForm):
    year = IntegerField(_l('Built year'), validators=[DataRequired()])
    size = IntegerField(_l('Size'), validators=[DataRequired()])
    use_size = IntegerField(_l('Usable size'), validators=[DataRequired()])
    rooms = IntegerField(_l('Rooms'), validators=[DataRequired()])
    bathrooms = IntegerField(_l('Bathrooms'), validators=[DataRequired()])
    balcony = BooleanField(_l('Balcony'))
    terrace = BooleanField(_l('Terrace'))
    patio = BooleanField(_l('Patio/Garden'))
    garage = BooleanField(_l('Garage'))
    elevator = BooleanField(_l('Elevator'))
    airconditioner = BooleanField(_l('Air Conditioner'))
    centralheating = BooleanField(_l('Central Heating'))
    energycert = SelectField(_l('Energy Eficiency Certificate'), choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H')])

class PropertySearch(FlaskForm):
    address = FormField(AddressForm)
    description = FormField(PropertyDescription)
    submit = SubmitField(_l('Submit'))

app/property/__init__.py
from flask import Blueprint

bp = Blueprint('property', __name__)

from app.property import routes

app/property/routes.py
from datetime import datetime
from flask import render_template, flash, redirect, url_for, request, g, \
    jsonify, current_app, json
import requests
from flask_login import current_user, login_required
from flask_principal import Principal, Permission, identity_loaded, RoleNeed, UserNeed
from flask_babel import _, get_locale
from guess_language import guess_language
from app import db
from app.models import User, Post, Message, Notification, Company, Role, UserRoles
from app.translate import translate
from app.main import bp
from app.property.forms import PropertySearch
from app.main.forms import SearchForm
from app.property import bp
from geopy.geocoders import Nominatim

@bp.before_app_request
def before_request():
    if current_user.is_authenticated:
        current_user.last_seen = datetime.utcnow()
        db.session.commit()
        g.search_form = SearchForm()
    g.locale = str(get_locale())

# Flask Principal
@identity_loaded.connect
def on_identity_loaded(sender, identity):
    # Set the identity user object
    identity.user = current_user

    # Add the UserNeed to the identity
    if hasattr(current_user, 'id'):
        identity.provides.add(UserNeed(current_user.id))

    # Assuming the User model has a list of roles, update the
    # identity with the roles that the user provides
    if hasattr(current_user, 'roles'):
        for role in current_user.roles:
            identity.provides.add(RoleNeed(role.name))

# Create a permission with a single Need, in this case a RoleNeed.
admin_permission = Permission(RoleNeed('admin'))

@bp.route('/', methods=['GET', 'POST'])
@bp.route('/index', methods=['GET', 'POST'])
@login_required
def property():
    form = PropertySearch()
    if form.validate_on_submit():
    #    flash(_('You searched for a Property'))
        return redirect(url_for('property.property_details'))
    return render_template('property/index.html', title=_('Home'), form=form, maptoken=current_app.config['MAPBOX_TOKEN'])

@bp.route('/georeference', methods=['POST'])
@login_required
def georeference():
    try:
        geolocator = Nominatim(user_agent="goodplaceindex/1")
        location = geolocator.geocode(request.form["text"])
        return jsonify(location.raw)
                #{'place_id': 138642704, 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright', 'osm_type': 'way', 'osm_id': 264768896, 'boundingbox': ['40.7407597', '40.7413004', '-73.9898715', '-73.9895014'], 'lat': '40.7410861', 'lon': '-73.9896298241625', 'display_name': 'Flatiron Building, 175, 5th Avenue, Flatiron District, Manhattan, Manhattan Community Board 5, New York County, NYC, New York, 10010, USA', 'class': 'tourism', 'type': 'attraction', 'importance': 0.793003315521974, 'icon': 'https://nominatim.openstreetmap.org/images/mapicons/poi_point_of_interest.p.20.png'}
    except Exception as e:
        #return str(e)
        return jsonify({'text': str(e)})

@bp.route('/details', methods=['GET', 'POST'])
@login_required
def property_details():
    prop_data = requests.get(request.url_root+'static/property_example.json').json()
    return render_template('property/details.html', title=_('Property details'), prop_data=prop_data)

app/templates/_dep_index.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>{{ _('Hi, %(username)s!', username=current_user.username) }}</h1>
    {% if form %}
    {{ wtf.quick_form(form) }}
    <br>
    {% endif %}
    {% for post in posts %}
        {% include '_post.html' %}
    {% endfor %}
    <nav aria-label="...">
        <ul class="pager">
            <li class="previous{% if not prev_url %} disabled{% endif %}">
                <a href="{{ prev_url or '#' }}">
                    <span aria-hidden="true">&larr;</span> {{ _('Newer posts') }}
                </a>
            </li>
            <li class="next{% if not next_url %} disabled{% endif %}">
                <a href="{{ next_url or '#' }}">
                    {{ _('Older posts') }} <span aria-hidden="true">&rarr;</span>
                </a>
            </li>
        </ul>
    </nav>
{% endblock %}

app/templates/_post.html
    <table class="table table-hover">
        <tr>
            <td width="70px">
                <a href="{{ url_for('main.user', username=post.author.username) }}">
                    <img src="{{ post.author.avatar(70) }}" />
                </a>
            </td>
            <td>
                {% set user_link %}
                    <span class="user_popup">
                        <a href="{{ url_for('main.user', username=post.author.username) }}">
                            {{ post.author.username }}
                        </a>
                    </span>
                {% endset %}
                {{ _('%(username)s said %(when)s',
                    username=user_link, when=moment(post.timestamp).fromNow()) }}
                <br>
                <span id="post{{ post.id }}">{{ post.body }}</span>
                {% if post.language and post.language != g.locale %}
                <br><br>
                <span id="translation{{ post.id }}">
                    <a href="javascript:translate(
                                '#post{{ post.id }}',
                                '#translation{{ post.id }}',
                                '{{ post.language }}',
                                '{{ g.locale }}');">{{ _('Translate') }}</a>
                </span>
                {% endif %}
            </td>
        </tr>
    </table>

app/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block title %}
    {% if title %}{{ title }} - Good Place{% else %}{{ _('Welcome to Good Place') }}{% endif %}
{% endblock %}

{% block navbar %}
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('main.index') }}">Good Place</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('main.index') }}">{{ _('Home') }}</a></li>
                    <li><a href="{{ url_for('main.explore') }}">{{ _('Explore') }}</a></li>
                </ul>
                {% if g.search_form %}
                <form class="navbar-form navbar-left" method="get" action="{{ url_for('main.search') }}">
                    <div class="form-group">
                        {{ g.search_form.q(size=20, class='form-control', placeholder=g.search_form.q.label.text) }}
                    </div>
                </form>
                {% endif %}
                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_anonymous %}
                    <li><a href="{{ url_for('auth.login') }}">{{ _('Login') }}</a></li>
                    {% else %}
                    <li>
                        <a href="{{ url_for('main.messages') }}">{{ _('Messages') }}
                            {% set new_messages = current_user.new_messages() %}
                            <span id="message_count" class="badge"
                                  style="visibility: {% if new_messages %}visible
                                                     {% else %}hidden{% endif %};">
                                {{ new_messages }}
                            </span>
                        </a>
                    </li>
                    <li><a href="{{ url_for('main.user', username=current_user.username) }}">{{ _('%(usr)s\'s profile', usr=current_user.username) }}</a></li>
                    {% if current_user.has_role('admin') %}
                      <li><a href="{{ url_for('admin.admin')}}">{{ _('Admin') }}</a></li>
                    {% endif %}
                    <li><a href="{{ url_for('auth.logout') }}">{{ _('Logout') }}</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
{% endblock %}

{% block content %}
    <div class="container">
        {% if current_user.is_authenticated %}
        {% with tasks = current_user.get_tasks_in_progress() %}
        {% if tasks %}
            {% for task in tasks %}
            <div class="alert alert-success" role="alert">
                {{ task.description }}
                <span id="{{ task.id }}-progress">{{ task.get_progress() }}</span>%
            </div>
            {% endfor %}
        {% endif %}
        {% endwith %}
        {% endif %}
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-info" role="alert">{{ message }}</div>
            {% endfor %}
        {% endif %}
        {% endwith %}

        {# application content needs to be provided in the app_content block #}
        {% block app_content %}{% endblock %}
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    {{ moment.include_moment() }}
    {{ moment.lang(g.locale) }}
    <script>
        function translate(sourceElem, destElem, sourceLang, destLang) {
            $(destElem).html('<img src="{{ url_for('static', filename='loading.gif') }}">');
            $.post('/translate', {
                text: $(sourceElem).text(),
                source_language: sourceLang,
                dest_language: destLang
            }).done(function(response) {
                $(destElem).text(response['text'])
            }).fail(function() {
                $(destElem).text("{{ _('Error: Could not contact server.') }}");
            });
        }
        $(function () {
            var timer = null;
            var xhr = null;
            $('.user_popup').hover(
                function(event) {
                    // mouse in event handler
                    var elem = $(event.currentTarget);
                    timer = setTimeout(function() {
                        timer = null;
                        xhr = $.ajax(
                            '/user/' + elem.first().text().trim() + '/popup').done(
                                function(data) {
                                    xhr = null;
                                    elem.popover({
                                        trigger: 'manual',
                                        html: true,
                                        animation: false,
                                        container: elem,
                                        content: data
                                    }).popover('show');
                                    flask_moment_render_all();
                                }
                            );
                    }, 1000);
                },
                function(event) {
                    // mouse out event handler
                    var elem = $(event.currentTarget);
                    if (timer) {
                        clearTimeout(timer);
                        timer = null;
                    }
                    else if (xhr) {
                        xhr.abort();
                        xhr = null;
                    }
                    else {
                        elem.popover('destroy');
                    }
                }
            );
        });
        function set_message_count(n) {
            $('#message_count').text(n);
            $('#message_count').css('visibility', n ? 'visible' : 'hidden');
        }
        function set_task_progress(task_id, progress) {
            $('#' + task_id + '-progress').text(progress);
        }
        {% if current_user.is_authenticated %}
        $(function() {
            var since = 0;
            setInterval(function() {
                $.ajax('{{ url_for('main.notifications') }}?since=' + since).done(
                    function(notifications) {
                        for (var i = 0; i < notifications.length; i++) {
                            switch (notifications[i].name) {
                                case 'unread_message_count':
                                    set_message_count(notifications[i].data);
                                    break;
                                case 'task_progress':
                                    set_task_progress(notifications[i].data.task_id,
                                        notifications[i].data.progress);
                                    break;
                            }
                            since = notifications[i].timestamp;
                        }
                    }
                );
            }, 10000);
        });
        {% endif %}
    </script>
    {% if request.blueprint == 'property' %}
      <script src="{{url_for('static', filename='leaflet/leaflet.js')}}"></script>
      <link rel="stylesheet" href="{{url_for('static', filename='leaflet/leaflet.css')}}">
      <script type="text/javascript">
        var mymap = L.map('map').setView([51.505, -0.09], 13);
        L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
          attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
          maxZoom: 18,
          id: 'mapbox.streets',
          accessToken: '{{ maptoken }}'
        }).addTo(mymap);
        var marker;
        function georeference(addressElem, destElem) {
           text = $('#address-street_name').val()+ ' '
             +$('#address-street_number').val()+ ' '
             +$('#address-city').val()+ ' '
             +$('#address-postalcode').val()+ ' '
             +$('#address-province').val()+ ' '
             +$('#address-region').val()+ ' '
             +$('#address-country').val();
            $(destElem).html('<img src="{{ url_for('static', filename='loading.gif') }}">');
            $.post('/property/georeference', {
                text: text
            }).done(function(response) {
                if(response != null){
                  $(destElem).html('place id: '+response['place_id']+'<br> lat: '+response['lat']+'<br> lon:'+response['lon'])
                  if(marker){ mymap.removeLayer(marker); }
                  mymap.setView(new L.LatLng(response['lat'], response['lon']), 15);
                  marker = L.marker([response['lat'], response['lon']]).addTo(mymap);
                }else{
                  $(destElem).html('{{ _('Try again') }}');
                }

            }).fail(function() {
                $(destElem).text("{{ _('Error: Could not contact server.') }}");
            });

        }
    </script>
    {% endif %}
{% endblock %}

app/templates/company.html
{% extends "base.html" %}

{% block app_content %}
    <table class="table table-hover">
        <tr>
            <td>
                <h1>{{ _('Company name') }}: {{ company.name }}</h1>
                {% if company.user_id %}
                <p>{{ _('Owner') }}: {{ company.owner.username }}</p>
                {% endif %}
                {% if company.membership_id %}
                <p>{{ _('Member ID') }}: {{ company.membership_id }}</p>
                {% endif %}
            </td>
        </tr>
    </table>
{% endblock %}

app/templates/edit_company.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>{{ _('Edit a company') }}</h1>
    <div class="row">
        <div class="col-md-4">
          {{ wtf.quick_form(form) }}
        </div>
        <div class="col-md-2">
          <img src="{{config.IMAGES_PATH+company.image}}" alt="{{company.name}}" width="100px">
        </div>
    </div>
    <a href="{{ url_for('main.delete_company', id=company.id) }}" class="btn btn-default">{{ _('Delete company') }}</a>

    <div class="row">
      <h2>{{ _('Subscriptions') }}</h2>
      {% if subsciptions %}{% endif %}
      <a href="{{ url_for('main.subscriptions', id=company.membership_id) }}" class="btn btn-default">{{ _('Add subscription plan') }}</a>
    </div>

    <div class="row">
      <h2>{{ _('Employees') }}</h2>
    <div class="col-md-4">
    {% for empl in company.employees %}
    <p><strong>{{ empl.username}}</strong> <a href="{{ url_for('main.company_fire', company_id=company.id, user_id=empl.id) }}" class="btn btn-small">{{ _('Fire employee') }}</a> </p>
    {% endfor %}
    </div>
    <div class="col-md-4">
    {% if current_user.has_role('admin') %}
    {% for futureuser in users %}
        {% if not company.is_employing(futureuser) %}
        <p>{{ futureuser.username }} {% if futureuser != current_user %} <a href="{{ url_for('main.company_hire', company_id=company.id, user_id=futureuser.id) }}">{{ _('Add employe') }}</a> {% else %} {{ _('It\'s You') }} {% endif %} </p>
        {% endif %}
    {% endfor %}
    {% endif %}
    </div>
    </div>

{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>{{ _('Hi, %(username)s!', username=current_user.username) }}</h1>
    {% if form %}
    {{ wtf.quick_form(form) }}
    <br>
    {% endif %}
    <a href="{{ url_for('property.property') }}">{{_('Go to property search')}}</a>

{% endblock %}

app/templates/messages.html
{% extends "base.html" %}

{% block app_content %}
    <h1>{{ _('Messages') }}</h1>
    {% for post in messages %}
        {% include '_post.html' %}
    {% endfor %}
    <nav aria-label="...">
        <ul class="pager">
            <li class="previous{% if not prev_url %} disabled{% endif %}">
                <a href="{{ prev_url or '#' }}">
                    <span aria-hidden="true">&larr;</span> {{ _('Newer messages') }}
                </a>
            </li>
            <li class="next{% if not next_url %} disabled{% endif %}">
                <a href="{{ next_url or '#' }}">
                    {{ _('Older messages') }} <span aria-hidden="true">&rarr;</span>
                </a>
            </li>
        </ul>
    </nav>
{% endblock %}

app/templates/new_company.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>{{ _('Create a company') }}</h1>
    <div class="row">
        <div class="col-md-4">
        {% if form %}  {{ wtf.quick_form(form) }} {% endif %}
        </div>
    </div>
{% endblock %}

app/templates/property.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
  <div>
    <p>Property ID= {{ prop_data.properties.property_id }}</p>
    <p>Property street= {{ prop_data.properties.property_address.street_name }}</p>
  </div>
{% endblock %}

app/templates/search.html
{% extends "base.html" %}

{% block app_content %}
    <h1>{{ _('Search Results') }}</h1>
    {% for post in posts %}
        {% include '_post.html' %}
    {% endfor %}
    <nav aria-label="...">
        <ul class="pager">
            <li class="previous{% if not prev_url %} disabled{% endif %}">
                <a href="{{ prev_url or '#' }}">
                    <span aria-hidden="true">&larr;</span> {{ _('Previous results') }}
                </a>
            </li>
            <li class="next{% if not next_url %} disabled{% endif %}">
                <a href="{{ next_url or '#' }}">
                    {{ _('Next results') }} <span aria-hidden="true">&rarr;</span>
                </a>
            </li>
        </ul>
    </nav>
{% endblock %}

app/templates/send_message.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>{{ _('Send Message to %(recipient)s', recipient=recipient) }}</h1>
    <div class="row">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
{% endblock %}

app/templates/subscriptions.html
{% extends "base.html" %}

{% block app_content %}
    <h1>{{ _('Subscription plans') }}</h1>
    <p>{{_('Subscription plans for')}}: {% if member.member_type == 'user'%}{{ member.username }} {% else %} {{ member.name }} {% endif %}</p>
    <div class="row">
      <div class="col-md-12">
        <h2>{{ _('Products') }}</h2>
        <table class="table table-striped">
          <thead>
            <tr>
            <th>#</th>
            <th>{{_('Name')}}</th>
            <th>{{_('Type')}}</th>
            <th>{{_('Price')}}</th>
            <th>{{_('Subscribe')}}</th>
            </tr>
          </thead>
        <tbody>
        {% for product in products %}
        {% if product.visible == True %}
        <tr>
          <th>{{ product.id }}</th>
          <td>
            <strong>{{product.name}}</strong>
          </td>
          <td>
            {{product.type}}
          </td>
          <td>
            € {{product.price}}
          </td>
          <td>
            {% for subs in subscriptions if subs.product_id == product.id %}
              {{ _('Already subscribed') }}
            {% else %}
              <a href="{{url_for('main.subscribe', product_id=product.id, membership_id=member.membership_id, )}}">{{_('Subscribe')}}</a>
            {% endfor %}
          </td>

        </tr>
        {% endif %}
        {% endfor %}
        </tbody>
      </table>
      </div>
    </div> <!-- Ends row -->

{% endblock %}

app/templates/user.html
{% extends "base.html" %}

{% block app_content %}
    <table class="table table-hover">
        <tr>
            <td width="256px"><img src="{{ user.avatar(256) }}"></td>
            <td>
                <h1>{{ _('User') }}: {{ user.username }}</h1>
                {% if user.membership %}<p>{{ ('You are the member'),  user.membership }}</p>{% endif %}
                {% if user.about_me %}<p>{{ user.about_me }}</p>{% endif %}
                {% if user.roles %}
                  {{_('Your roles are: ')}}{{ user.roles|join(', ', attribute='name') }}
                {% endif %}
                {% if user.last_seen %}
                <p>{{ _('Last seen on') }}: {{ moment(user.last_seen).format('LLL') }}</p>
                {% endif %}
                {% if companies.count() > 0 %}
                <p>
                  {% set comma = joiner(", ") %}
                  {{ _('Companies you own:') }}
                  {% for company in companies %}
                  {{ comma() }}<a href="{{ url_for('main.edit_company', id=company.id) }}">{{ company.name }}</a>
                  {% endfor %}
                </p>
                {% else %}
                  <p>{{ _('No companies to show') }}</p>
                {% endif %}
                <p><a href="{{ url_for('main.new_company') }}" class="btn btn-default">{{ _('Create new company') }}</a></p>
                <p>{{ _('%(count)d followers', count=user.followers.count()) }}, {{ _('%(count)d following', count=user.followed.count()) }}</p>
                {% if user == current_user %}
                <p><a href="{{ url_for('main.edit_profile') }}" class="btn btn-default">{{ _('Edit your profile') }}</a></p>
                {% if not current_user.get_task_in_progress('export_posts') %}
                <p><a href="{{ url_for('main.export_posts') }}" class="btn btn-default disabled">{{ _('Export your posts') }}</a></p>
                {% endif %}
                {% elif not current_user.is_following(user) %}
                <p><a href="{{ url_for('main.follow', username=user.username) }}">{{ _('Follow') }}</a></p>
                {% else %}
                <p><a href="{{ url_for('main.unfollow', username=user.username) }}">{{ _('Unfollow') }}</a></p>
                {% endif %}
                {% if user != current_user %}
                <p><a href="{{ url_for('main.send_message', recipient=user.username) }}">{{ _('Send private message') }}</a></p>
                {% endif %}
            </td>
        </tr>
    </table>
    {% for post in posts %}
        {% include '_post.html' %}
    {% endfor %}
    <nav aria-label="...">
        <ul class="pager">
            <li class="previous{% if not prev_url %} disabled{% endif %}">
                <a href="{{ prev_url or '#' }}">
                    <span aria-hidden="true">&larr;</span> {{ _('Newer posts') }}
                </a>
            </li>
            <li class="next{% if not next_url %} disabled{% endif %}">
                <a href="{{ next_url or '#' }}">
                    {{ _('Older posts') }} <span aria-hidden="true">&rarr;</span>
                </a>
            </li>
        </ul>
    </nav>
{% endblock %}

app/templates/user_popup.html
<table class="table">
    <tr>
        <td width="64" style="border: 0px;"><img src="{{ user.avatar(64) }}"></td>
        <td style="border: 0px;">
            <p><a href="{{ url_for('main.user', username=user.username) }}">{{ user.username }}</a></p>
            <small>
                {% if user.about_me %}<p>{{ user.about_me }}</p>{% endif %}
                {% if user.last_seen %}
                <p>{{ _('Last seen on') }}: {{ moment(user.last_seen).format('lll') }}</p>
                {% endif %}
                <p>{{ _('%(count)d followers', count=user.followers.count()) }}, {{ _('%(count)d following', count=user.followed.count()) }}</p>
                {% if user != current_user %}
                    {% if not current_user.is_following(user) %}
                    <a href="{{ url_for('main.follow', username=user.username) }}">{{ _('Follow') }}</a>
                    {% else %}
                    <a href="{{ url_for('main.unfollow', username=user.username) }}">{{ _('Unfollow') }}</a>
                    {% endif %}
                {% endif %}
            </small>
        </td>
    </tr>
</table>